Update Android build workflow for main branch

diff --git a/.github/workflows/android_build.yml b/.github/workflows/android_build.yml
--- a/.github/workflows/android_build.yml
+++ b/.github/workflows/android_build.yml
@@ -1,11 +1,16 @@
 name: Android Build
-on: [push, workflow_dispatch]
+on:
+  workflow_dispatch:
+  push:
+    branches:
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
       - name: set up JDK 17
         uses: actions/setup-java@v3
@@ -19,7 +24,7 @@ jobs:
       - name: Build Web Project
         run: |
           mkdir -p www
-          [ -f index.html ] && cp index.html www/ || echo "No index.html"
+          [ -f index.html ] && cp index.html www/ || echo "index.html not found"
 
       - name: Install Capacitor Android
         run: npm install @capacitor/android
